// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(KlepaDbContext))]
    [Migration("20230313165654_ChannelsSetupAdded")]
    partial class ChannelsSetupAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("DataAccess.Models.ChannelsSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddToPrivateChannelCounter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddToPublicChannelCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateChannelDefaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PrivateMotherChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicChannelDefaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PublicMotherChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChannelsSetup");
                });

            modelBuilder.Entity("DataAccess.Models.Server", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsSetupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelsSetupId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("DataAccess.Models.Server", b =>
                {
                    b.HasOne("DataAccess.Models.ChannelsSetup", "ChannelsSetup")
                        .WithMany()
                        .HasForeignKey("ChannelsSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelsSetup");
                });
#pragma warning restore 612, 618
        }
    }
}
